BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE NT_USERS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE <> -942 and SQLCODE <> -2449 THEN
      RAISE;
    END IF;
END;
/
CREATE TABLE NT_USERS(
  USER_ID VARCHAR(50) NOT NULL,
  FIRSTNAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50),
  USERNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  CREATED_AT DATE DEFAULT NULL,
  UPDATED_AT DATE DEFAULT NULL,
  CONSTRAINT PK_NT_USERS_USER_ID PRIMARY KEY (USER_ID),
  CONSTRAINT UK_NT_USERS_USERNAME UNIQUE (USERNAME),
  CONSTRAINT UK_NT_USERS_EMAIL UNIQUE (EMAIL)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE NT_ROLES CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE <> -942 and SQLCODE <> -2449 THEN
      RAISE;
    END IF;
END;
/
CREATE TABLE NT_ROLES (
  ROLE_ID VARCHAR(50) NOT NULL,
  ROLE_NAME VARCHAR(60) NOT NULL,
  ROLE_DESCRITION VARCHAR(60),
  CONSTRAINT PK_NT_ROLES_ROLE_ID PRIMARY KEY (ROLE_ID),
  CONSTRAINT UK_NT_ROLES_ROLES_NAME UNIQUE (ROLE_NAME)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE NT_USER_ROLES CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE <> -942 and SQLCODE <> -2449 THEN
      RAISE;
    END IF;
END;
/
CREATE TABLE NT_USER_ROLES (
  USER_ID VARCHAR(50) NOT NULL,
  ROLE_ID VARCHAR(50) NOT NULL,
  CONSTRAINT PK_NT_USER_ROLES PRIMARY KEY (USER_ID,ROLE_ID),
  CONSTRAINT FK_NT_USER_ROLES_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES NT_ROLES (ROLE_ID),
  CONSTRAINT FK_NT_USER_ROLES_USER_ID FOREIGN KEY (USER_ID) REFERENCES NT_USERS (USER_ID)
);
